# Python_NumPy

## 1.基本数据类型

- 数字：整型和浮点型(int and float)

In [1]:
x = 3
print(type(x)) # Prints "<class 'int'>"
print(x)       # Prints "3"
print(x + 1)   # 加; prints "4"
print(x - 1)   # 减; prints "2"
print(x * 2)   # 乘; prints "6"
print(x ** 2)  # 平方; prints "9"
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"
y = 2.5
print(type(y)) # Prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


**注意：python没有自增和自减运算符 如c++，c--**

- bool值

In [2]:
t = True
f = False
print(type(t)) # Prints "<class 'bool'>"
print(t and f) # 两者同时满足 逻辑"与" ; prints "False"
print(t or f)  # 两者满足其一 逻辑"或" ; prints "True"
print(not t)   # 不满足t是否正确 逻辑"非" ; prints "False"
print(t != f)  # 不等于 ; prints "True"

<class 'bool'>
False
True
False
True


**注：python 实现了布尔逻辑的所有常用运算符，但使用英语单词（and,or,not）而不是符号 如：&&，||等**

- 字符串(string)

In [3]:
hello = 'hello'    # 单引号引用
world = "world"    # 双引号引用也可以 这无所谓
print(hello)       # Prints "hello"
print(len(hello))  # 字符串的长度 ; prints "5"
hw = hello + ' ' + world  # 字符串相加
print(hw)  # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12)  # 字符串中的数据可以是不同类型的
print(hw12)  # prints "hello world 12"

hello
5
hello world
hello world 12


**string对象有很多有用的方法 例如：**

In [4]:
s = "hello"
print(s.capitalize())  # 首字母大写输出 ; prints "Hello"
print(s.upper())       # 大写所有字母 ; prints "HELLO"
print(s.rjust(7))      # 右对齐 不足部分空格填充 总长度7 ; prints "  hello"
print(s.center(7))     # 居中 不足部分空格填充 总长度7 ; prints " hello "
print(s.replace('l', '(ell)'))  # 把指定字符串用后一个字符串代替;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # 去除首尾的空白字符 ; prints "world"

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


## 2.容器

- 列表(list)：列表相当于 Python 的数组，但可以调整大小并且可以包含不同类型的元素

In [5]:
xs = [3, 1, 2]    # 创建一个列表
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # 负索引从列表末尾开始计数 末尾是-1 ; prints "2"
xs[2] = 'foo'     # 列表可以包含不同类型的元素
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # 向列表末尾添加一个新元素
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # 弹出并用'x'接收列表的最后一个元素
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [6]:
nums = list(range(5))     # range 是一个内置函数，用于创建整数列表 不超过括号内的整数
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # 获取从索引 2 到 4（不包含 4）的切片; prints "[2, 3]"
print(nums[2:])           # 获取从索引 2 到 结尾 的切片; prints "[2, 3, 4]"
print(nums[:2])           # 获取从开头到索引 2（不包含 2）的切片; prints "[0, 1]"
print(nums[:])            # 获取整个列表 相当于 print(nums); prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # 切片索引可以是负数（-1 表示最后一个元素） 这里不取最后一个数 ; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # 给切片赋值一个新的子列表
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**共性：切片的标志是 [ : ] 且在范围中取前不取后**

In [7]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print(animal)
# Prints "cat", "dog", "monkey", 每个元素单占一行

cat
dog
monkey


**可使用enumerate()函数获取键值对元组(index, value)**

In [8]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


列表推导式：

In [9]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


等同于：

In [10]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)   # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


列表推导式也可以加条件：

In [11]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print(even_squares)  # Prints "[0, 4, 16]"

[0, 4, 16]


**注：与不可变的元组作区分，[]为可变，()为不可变**

- 字典(dict)

In [12]:
d = {'cat': 'cute', 'dog': 'furry'}  # 创建一个字典
print(d['cat'])       # 由键得到值 ; prints "cute"
print('cat' in d)     # 检查'cat' 是否在d中 ; prints "True"
d['fish'] = 'wet'     # 增加（或更新）元素
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # 获取指定键的值，若键不存在则返回默认值'N/A' ; prints "N/A"
print(d.get('fish', 'N/A'))    # 获取指定键的值，若键不存在则返回默认值'N/A' ; prints "wet"
del d['fish']         # 根据键删除dict中的元素
print(d.get('fish', 'N/A')) # fish 不再是一个键 ; prints "N/A"

cute
True
wet
N/A
wet
N/A


**key类型：必须是不可变类型（如 int、str、tuple 等），确保哈希稳定。**

**value类型：可以是任何类型（包括可变类型），完全灵活。**

循环输出字典中的元素：

In [13]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


item函数可以返回键和值：

In [14]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

A person has 2 legs
A cat has 4 legs
A spider has 8 legs



字典推导式:

In [15]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)  # Prints "{0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


- 集合(set)

**无序且唯一**

In [16]:
animals = {'cat', 'dog'}
print('cat' in animals)   # 检查元素是否在集合中 ; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # 向集合中添加元素
print('fish' in animals)  # Prints "True"
print(len(animals))       # 输出集合的长度 ; prints "3"
animals.add('cat')        # 向集合添加一个已有的元素
print(len(animals))       # Prints "3"
animals.remove('cat')     # 删除集合中的元素
print(len(animals))       # Prints "2"

True
False
True
3
3
2


**循环：集合与列表具有相同的语法 ; 但是，集合是无序的，无法按照指定顺序访问**

In [17]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: dog
#2: cat
#3: fish


集合推导式：

In [18]:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums)  # Prints "{0, 1, 2, 3, 4, 5}"

{0, 1, 2, 3, 4, 5}


- 元组(tuple)

**和列表类似 但元组不可变 元组可以用作字典中的键和集合的元素，而列表不能**

In [19]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


### 容器特性总结

| 特性               | 列表（list）               | 元组（tuple）               | 集合（set）                 |
|--------------------|---------------------------|---------------------------|---------------------------|
| **定义方式**       | 用方括号 `[]`             | 用圆括号 `()`（可省略）     | 用花括号 `{}` 或 `set()`   |
| **可变性**         | 可变（可增删改元素）       | 不可变（创建后不能修改）     | 可变（可增删元素）         |
| **有序性**         | 有序（元素有固定位置）     | 有序（元素有固定位置）       | 无序（元素无固定位置）     |
| **元素唯一性**     | 允许重复元素               | 允许重复元素               | 不允许重复元素（自动去重） |
| **索引/切片**      | 支持（因有序）             | 支持（因有序）              | 不支持（因无序）           |
| **常用场景**       | 需动态修改的序列（如日志） | 固定数据（如坐标、配置项）   | 去重、集合运算（交/并/差） |

## 3.类

In [20]:
class Greeter(object):     # 定义一个 Greeter 类，继承自 object（Python 中所有类的基类）   

    # 初始化方法
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # 实例方法
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # 创建 Greeter 类的一个实例（对象），传入参数 'Fred'
g.greet()            # 调用实例方法 greet() ; prints "Hello, Fred"
g.greet(loud=True)   # 调用实例方法 greet() ; prints "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


和c++一样，类也有封装，继承，多态三大特性

## 4.Numpy 

### 4.1 简介

NumPy（Numerical Python 的缩写）是 Python 中用于科学计算的核心库，主要用于处理大型多维数组（矩阵）和执行高效的数值运算。它是数据分析、机器学习、深度学习、科学计算等领域的基础工具，许多高级库（如 Pandas、Matplotlib、TensorFlow 等）都依赖于 NumPy 的底层功能。

### 4.2 矩阵

numpy 数组是一个值网格，所有值都具有相同的类型，并由非负整数的元组索引。维数是数组的等级;数组的形状是一个整数元组，给出了数组沿每个维度的大小。
numpy效率高的原因是用c语言写的，可以结合c中（二维）数组更好理解。

我们可以从嵌套的 Python 列表中初始化 numpy 数组，并使用方括号访问元素：

In [21]:
import numpy as np

a = np.array([1, 2, 3])   # 创建一个一维数组（秩为1的数组）,可以传入列表元组
print(type(a))            # 输出a的类型 ; Prints "<class 'numpy.ndarray'>"
print(a.shape)            # shape 是数组的属性，返回一个元组，表示有几行几列（逗号表示这是一个元组，而非普通括号）
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # 修改数组的元素
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # 创建一个二维数组
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


其他创建数组方法：

In [22]:
import numpy as np

a = np.zeros((2,2))   # 创建一个 2x2 的全零数组
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # 创建一个 1x2 的全一数组
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # 创建一个 2x2 的常量数组，元素全为 7
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # 创建一个 2x2 的单位矩阵
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # 创建一个 2x2 的数组，元素为 [0,1) 之间的随机浮点数 相当于：np.random.rand(2,2)
print(e)                     # 可能输出 "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.05329233 0.50550716]
 [0.45988266 0.38721269]]


数组索引：

Numpy 提供了多种索引数组的方法。

切片：与 Python 列表类似，可以对 numpy 数组进行切片。由于数组可能是多维的，因此数组的每个维度都要指定一个切片操作：

In [23]:
import numpy as np

# 3行4列的二维数组 
#  [ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9  10 11 12]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 用切片操作提取出由前 2 行以及第 1 列和第 2 列组成的子数组；其中 b 是下方这个形状为 (2, 2) 的数组 ','前为行的切片，','后为列的切片
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# 数组的切片会改变原始数组
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] 与 a[0, 1] 指向同一块数据
print(a[0, 1])   # Prints "77"

2
77


索引与切片索引混合使用：

In [24]:
import numpy as np

# 初始化一个三行四列的二维数组
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 两种获取数组中间行数据的方式。
# 整数索引与切片混合使用会得到一个低维度的数组，
# 而仅使用切片会得到与原数组维度相同的数组：
row_r1 = a[1, :]    # 取数组的第一行，变为一维数组
row_r2 = a[1:2, :]  # 取数组的第二行（注意两者的shape）
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# 获取数组列时也有同样的区别
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**注：索引和切片混合使用会降维度，若想达到相同效果可以两次切片（即用切片代替索引）**

整数数组索引：

In [25]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# 整数数组索引的示例。
# 返回的数组形状为 (3,)，并且
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# 上面的整数数组索引示例等价于：
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# 使用整数数组索引时，可以重复使用源数组中的同一个元素：
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# 与前一个整数数组索引示例等价
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


**注意[]的位置**

整数数组索引的一个有用技巧是从矩阵的每一行中选择或更改一个元素：

In [26]:
import numpy as np

a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"


b = np.array([0, 2, 0, 1])

# 利用数组 b 中的索引，从数组 a 的每一行选取一个元素
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# 利用数组 b 中的索引，修改数组 a 每一行的一个元素
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


数据类型：

每个 numpy 数组都是相同类型元素的网格。Numpy 提供了大量可用于构造数组的数字数据类型。Numpy 在创建数组时会尝试猜测数据类型，但构造数组的函数通常还包含一个可选参数来指定数据类型。这是一个例子：

In [27]:
import numpy as np

x = np.array([1, 2])   # 猜测数据类型
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # 猜测数据类型
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # 指定数据类型（注意格式）
print(x.dtype)                         # Prints "int64"

int64
float64
int64


## 4.3 运算

In [28]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 加
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# 减
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# 乘
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# 除
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# 开方
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [29]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# 向量的内积；两者都输出 219
print(v.dot(w))
print(np.dot(v, w))

# 矩阵与向量的乘积；两者都输出一维数组 [29 67]
print(x.dot(v))
print(np.dot(x, v))

# 矩阵与矩阵的乘积；两者都输出二维数组
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


**注:np.dot()参数顺序非常重要**

In [30]:
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 计算所有元素的总和；输出 "10"
print(np.sum(x, axis=0))  # 计算每一列的总和；Print "[4 6]"   axis意思为轴线
print(np.sum(x, axis=1))  # 计算每一行的总和；Print "[3 7]"

10
[4 6]
[3 7]


In [31]:
import numpy as np
# 求转置
x = np.array([[1,2], [3,4]])
print(x)    # 输出 "[[1 2]
            #          [3 4]]"
print(x.T)  # 输出 "[[1 3]
            #          [2 4]]"

# 注意：对一维数组求转置不会产生任何变化
v = np.array([1,2,3])
print(v)    # 输出 "[1 2 3]"
print(v.T)  # 输出 "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


广播(Broadcasting)：

在 NumPy 中，广播（Broadcasting） 是一种自动处理不同形状数组之间算术运算的机制。它的核心思想是：当两个数组形状不同时，NumPy 会尝试通过扩展其中一个或两个数组的维度（虚拟地增加尺寸，不实际复制数据），使它们的形状兼容，从而进行 element-wise（元素级）运算。

方法一：(循环)

In [32]:
import numpy as np

# 我们会将向量 v 加到矩阵 x 的每一行上，
# 并将结果存储在矩阵 y 中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # 创建一个与 x 形状相同的空矩阵

# 通过显式循环，将向量 v 加到矩阵 x 的每一行
for i in range(4):
    y[i, :] = x[i, :] + v

# 此时 y 的结果如下
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


方法二：(副本)

In [33]:
import numpy as np

# 我们会将向量 v 加到矩阵 x 的每一行上，
# 并将结果存储在矩阵 y 中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # 将 v 堆叠 4 份（按行复制 4 次）
print(vv)                 # Print "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # 对 x 和 vv 进行元素级加法
print(y)  # Print "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


方法三：(broadcasting)

In [34]:
import numpy as np

# 我们会将向量 v 加到矩阵 x 的每一行上，
# 并将结果存储在矩阵 y 中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # 利用广播机制将 v 加到 x 的每一行
print(y)  # 输出 "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


方法三相当于方法二，但在写法上更简单

广播的一些应用：

In [35]:
import numpy as np

# 计算向量的外积
v = np.array([1,2,3])  # v 的形状为 (3,)
w = np.array([4,5])    # w 的形状为 (2,)
# 要计算外积，首先将 v 重塑为形状为 (3, 1) 的列向量；
# 然后可以将其与 w 进行广播，得到形状为 (3, 2) 的输出，即 v 和 w 的外积：
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# 向矩阵的每一行添加一个向量
x = np.array([[1,2,3], [4,5,6]])
# x 的形状为 (2, 3)，v 的形状为 (3,)，因此它们可以广播为 (2, 3)，
# 得到以下矩阵：
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# 向矩阵的每一列添加一个向量
# x 的形状为 (2, 3)，w 的形状为 (2,)。
# 如果转置 x，其形状变为 (3, 2)，可以与 w 广播得到形状为 (3, 2) 的结果；
# 再转置该结果，得到形状为 (2, 3) 的最终结果，即每一列都添加了向量 w 的矩阵 x。
# 得到以下矩阵：
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# 另一种解决方案是将 w 重塑为形状为 (2, 1) 的列向量；
# 然后可以直接将其与 x 广播，产生相同的输出。
print(x + np.reshape(w, (2, 1)))

# 矩阵与常数相乘：
# x 的形状为 (2, 3)。NumPy 将标量视为形状为 () 的数组；
# 它们可以一起广播为 (2, 3) 的形状，产生以下数组：
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


两个三维向量外积：

In [36]:
import numpy as np

# 定义两个三维向量
a = np.array([1, 2, 3])  # 向量 a = (1, 2, 3)
b = np.array([4, 5, 6])  # 向量 b = (4, 5, 6)

# 计算叉乘
c = np.cross(a, b)

print("a × b =", c)  # 输出：[ -3   6  -3 ]

a × b = [-3  6 -3]


广播通常会使代码更简洁、更快速，因此应尽可能使用它。

### 数组总结（from:豆包）

NumPy 是 Python 中用于科学计算的核心库，提供了高效的多维数组对象和大量用于数组操作的函数。以下是一些常用函数的分类整理：


### **一、数组创建函数**
1. **`numpy.array()`**  
   从列表或元组创建数组：  
   ```python
   import numpy as np
   arr = np.array([1, 2, 3])  # 一维数组
   arr2d = np.array([[1, 2], [3, 4]])  # 二维数组
   ```

2. **`numpy.zeros()` / `numpy.ones()`**  
   创建全 0 或全 1 数组：  
   ```python
   zeros = np.zeros((2, 3))  # 2行3列的全0数组
   ones = np.ones((3, 3))   # 3x3的全1数组
   ```

3. **`numpy.arange()`**  
   生成等差数列（类似 Python 内置 `range`，但返回数组）：  
   ```python
   arr = np.arange(0, 10, 2)  # [0, 2, 4, 6, 8]
   ```

4. **`numpy.linspace()`**  
   生成指定数量的等间隔数值：  
   ```python
   arr = np.linspace(0, 1, 5)  # [0.  , 0.25, 0.5 , 0.75, 1.  ]
   ```

5. **`numpy.eye()`**  
   创建单位矩阵（对角线为 1，其余为 0）：  
   ```python
   eye = np.eye(3)  # 3x3单位矩阵
   ```


### **二、数组属性与形状操作**
1. **`shape` / `dtype` / `ndim`**  
   数组的形状、数据类型、维度：  
   ```python
   arr = np.array([[1, 2], [3, 4]])
   print(arr.shape)  # (2, 2)
   print(arr.dtype)  # int64
   print(arr.ndim)   # 2（二维）
   ```

2. **`reshape()`**  
   改变数组形状（元素总数不变）：  
   ```python
   arr = np.arange(6).reshape(2, 3)  # 2行3列：[[0,1,2],[3,4,5]]
   ```

3. **`flatten()` / `ravel()`**  
   将多维数组展平为一维：  
   ```python
   arr = np.array([[1, 2], [3, 4]])
   print(arr.flatten())  # [1 2 3 4]
   ```

4. **`transpose()` 或 `T`**  
   数组转置（行变列，列变行）：  
   ```python
   arr = np.array([[1, 2], [3, 4]])
   print(arr.T)  # [[1 3], [2 4]]
   ```


### **三、数组运算函数**
1. **element-wise 运算**  
   直接用算术运算符（`+`, `-`, `*`, `/`）或对应函数：  
   ```python
   a = np.array([1, 2, 3])
   b = np.array([4, 5, 6])
   print(a + b)       # [5 7 9]
   print(np.add(a, b))  # 同上
   ```

2. **矩阵乘法**  
   `dot()` 或 `@` 运算符：  
   ```python
   a = np.array([[1, 2], [3, 4]])
   b = np.array([[5, 6], [7, 8]])
   print(a @ b)       # 矩阵乘法
   print(np.dot(a, b))  # 同上
   ```

3. **广播（Broadcasting）**  
   自动扩展维度不同的数组进行运算：  
   ```python
   a = np.array([[1, 2], [3, 4]])
   b = np.array([10, 20])
   print(a + b)  # [[11, 22], [13, 24]]
   ```


### **四、统计与聚合函数**
1. **`sum()` / `mean()` / `median()`**  
   求和、平均值、中位数：  
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr.sum())    # 15
   print(arr.mean())   # 3.0
   print(np.median(arr))  # 3.0
   ```

2. **`max()` / `min()` / `argmax()` / `argmin()`**  
   最大值、最小值、最大值索引、最小值索引：  
   ```python
   arr = np.array([3, 1, 4, 2])
   print(arr.max())    # 4
   print(arr.argmax()) # 2（索引从0开始）
   ```

3. **`std()` / `var()`**  
   标准差、方差：  
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   print(arr.std())    # 1.414...
   print(arr.var())    # 2.0
   ```


### **五、数组索引与切片**
1. **基础索引**  
   类似列表，支持多维索引：  
   ```python
   arr = np.array([[1, 2, 3], [4, 5, 6]])
   print(arr[0, 1])  # 2（第0行第1列）
   ```

2. **切片**  
   提取子数组：  
   ```python
   arr = np.arange(10)
   print(arr[2:5])   # [2, 3, 4]
   print(arr[:6:2])  # [0, 2, 4]（步长为2）
   ```

3. **布尔索引**  
   根据条件筛选元素：  
   ```python
   arr = np.array([1, 2, 3, 4, 5])
   mask = arr > 3
   print(arr[mask])  # [4, 5]
   ```


### **六、其他常用函数**
1. **`numpy.concatenate()`**  
   拼接数组：  
   ```python
   a = np.array([1, 2])
   b = np.array([3, 4])
   print(np.concatenate([a, b]))  # [1, 2, 3, 4]
   ```

2. **`numpy.random` 模块**  
   生成随机数：  
   ```python
   np.random.seed(42)  # 固定随机种子
   print(np.random.rand(2, 2))  # 2x2的[0,1)随机数
   print(np.random.randint(0, 10, size=3))  # [3个0-10的整数]
   ```

3. **`numpy.where()`**  
   条件判断，类似三目运算符：  
   ```python
   arr = np.array([1, 2, 3, 4])
   print(np.where(arr > 2, arr, 0))  # [0, 0, 3, 4]
   ```


以上是 NumPy 的核心常用函数，覆盖了数组创建、操作、运算和统计等场景。

图像也是一种Arrary 可以通过pillow库，OpenCV库等进行读取并用numpy进行处理

#### Ps:本文只选了部分有代表性的实例，其余用法可以参考[官方文档](https://numpy.org/doc/)